/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ExportList = function ExportList(pk, list) {
    this.init.call(this, pk, list);
};

ExportList.prototype = new ExportListBase();
ExportList.prototype.constructor = ExportList;
exports.ExportList = ExportList;