/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ExportModel = function ExportModel() {
};

ExportModel.prototype = new ExportModelBase();
ExportModel.prototype.constructor = ExportModel;
exports.ExportModel = new ExportModel();