/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ExportListModel = function ExportListModel() {
};

ExportListModel.prototype = new ExportListModelBase();
ExportListModel.prototype.constructor = ExportListModel;
exports.ExportListModel = new ExportListModel();