/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Export = function Export(args) {
    this.init.call(this, args);
};

Export.prototype = new ExportBase();
Export.prototype.constructor = Export;
exports.Export = Export;