/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ExportConfigModel = function ExportConfigModel() {
};

ExportConfigModel.prototype = new ExportConfigModelBase();
ExportConfigModel.prototype.constructor = ExportConfigModel;
exports.ExportConfigModel = new ExportConfigModel();