/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var StructureList = function StructureList(pk, list) {
    this.init.call(this, pk, list);
};

StructureList.prototype = new StructureListBase();
StructureList.prototype.constructor = StructureList;
exports.StructureList = StructureList;