/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Structure = function Structure(args) {
    this.init.call(this, args);
};

Structure.prototype = new StructureBase();
Structure.prototype.constructor = Structure;
exports.Structure = Structure;