/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var StructureListModel = function StructureListModel() {
};

StructureListModel.prototype = new StructureListModelBase();
StructureListModel.prototype.constructor = StructureListModel;
exports.StructureListModel = new StructureListModel();