/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var TableListModel = function TableListModel() {
};

TableListModel.prototype = new TableListModelBase();
TableListModel.prototype.constructor = TableListModel;
exports.TableListModel = new TableListModel();