/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Table = function Table(args) {
    this.init.call(this, args);
};

Table.prototype = new TableBase();
Table.prototype.constructor = Table;
exports.Table = Table;