/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var TableModel = function TableModel() {
};

TableModel.prototype = new TableModelBase();
TableModel.prototype.constructor = TableModel;
exports.TableModel = new TableModel();