exports.orms = [
{
    name: 'Table',
    abb: 't',
    column: [
        'id',
        'name',
        'description',
    ],
    toAddFilter: [],
    toUpdateFilter: [0],
    toAbbFilter: [],
    toArrayFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'TableList',
},
{
    name: 'Column',
    abb: 'c',
    column: [
        'id',
        'name',
        'isPK',
        'allowEmpty',
        'type',
        'client',
        'server',
        'description',
    ],
    toAddFilter: [],
    toUpdateFilter: [0],
    toAbbFilter: [],
    toArrayFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'ColumnList',
},
    /*
{
    name: 'Export',
    abb: 'e',
    column: [
        'id',
        'name',
        'sort',
        'description',
    ],
    updateFilter: [0],
    clientFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'ExportList',
},
{
    name: 'ExportConfig',
    abb: 'ec',
    column: [
        'id',
        'path',
        'fileName',
        'graphTableIds',
        'graphStructure',
        'columnDetail',
        'canvas',
    ],
    updateFilter: [0],
    clientFilter: [],
    pk: 'id',
    pkAutoIncrement: false,
    list: null,
},
*/
];
