/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ColumnListModel = function ColumnListModel() {
};

ColumnListModel.prototype = new ColumnListModelBase();
ColumnListModel.prototype.constructor = ColumnListModel;
exports.ColumnListModel = new ColumnListModel();