/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Column = function Column(args) {
        this.init.call(this, args);
    };

    Column.prototype = new I.Models.ColumnBase();
    Column.prototype.constructor = Column;

    I.Util.require('Column', 'Models', Column);
}();