/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Column = function Column(args) {
    this.init.call(this, args);
};

Column.prototype = new ColumnBase();
Column.prototype.constructor = Column;
exports.Column = Column;