/* This file is generated by IFramework - Maker.js for user to rewrite PKStore file */
!function () {
    var ColumnPKStore = function ColumnPKStore(db) {
        this.db = db;
    };

    ColumnPKStore.prototype = new I.Models.ColumnPKStoreBase();
    ColumnPKStore.prototype.constructor = ColumnPKStore;

    I.Util.require('ColumnPKStore', 'Models', new ColumnPKStore(db));
}();