/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ColumnList = function ColumnList(pk, list) {
    this.init.call(this, pk, list);
};

ColumnList.prototype = new ColumnListBase();
ColumnList.prototype.constructor = ColumnList;
exports.ColumnList = ColumnList;