/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var ColumnPK = function ColumnPK(pk) {
        this.init.call(this, pk);
    };

    ColumnPK.prototype = new I.Models.ColumnPKBase();
    ColumnPK.prototype.constructor = ColumnPK;

    I.Util.require('ColumnPK', 'Models', ColumnPK);
}();