/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ColumnModel = function ColumnModel() {
};

ColumnModel.prototype = new ColumnModelBase();
ColumnModel.prototype.constructor = ColumnModel;
exports.ColumnModel = new ColumnModel();