/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var ColumnStore = function ColumnStore(db) {
    this.db = db;
    };

    ColumnStore.prototype = new I.Models.ColumnStoreBase();
    ColumnStore.prototype.constructor = ColumnStore;

    I.Util.require('ColumnStore', 'Models', new ColumnStore(db));
}();