/* This file is generated by IFramework - Maker.js for user to rewrite List file */
!function () {
    var ExporterList = function ExporterList(pk, list) {
        this.init.call(this, pk, list);
    };

    ExporterList.prototype = new I.Models.ExporterListBase();
    ExporterList.prototype.constructor = ExporterList;

    I.Util.require('ExporterList', 'Models', ExporterList);
}();