/* This file is generated by IFramework - Maker.js for user to rewrite PKStore file */
!function () {
    var ExporterPKStore = function ExporterPKStore(db) {
        this.db = db;
    };

    ExporterPKStore.prototype = new I.Models.ExporterPKStoreBase();
    ExporterPKStore.prototype.constructor = ExporterPKStore;

    I.Util.require('ExporterPKStore', 'Models', new ExporterPKStore(db));
}();