/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var ExporterExistColumnPK = function ExporterExistColumnPK(pk) {
        this.init.call(this, pk);
    };

    ExporterExistColumnPK.prototype = new I.Models.ExporterExistColumnPKBase();
    ExporterExistColumnPK.prototype.constructor = ExporterExistColumnPK;

    I.Util.require('ExporterExistColumnPK', 'Models', ExporterExistColumnPK);
}();