/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var ExporterStore = function ExporterStore(db) {
    this.db = db;
    };

    ExporterStore.prototype = new I.Models.ExporterStoreBase();
    ExporterStore.prototype.constructor = ExporterStore;

    I.Util.require('ExporterStore', 'Models', new ExporterStore(db));
}();