/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var ExporterExistColumnStore = function ExporterExistColumnStore(db) {
    this.db = db;
    };

    ExporterExistColumnStore.prototype = new I.Models.ExporterExistColumnStoreBase();
    ExporterExistColumnStore.prototype.constructor = ExporterExistColumnStore;

    I.Util.require('ExporterExistColumnStore', 'Models', new ExporterExistColumnStore(db));
}();