/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var ExportConfig = function ExportConfig(args) {
    this.init.call(this, args);
};

ExportConfig.prototype = new ExportConfigBase();
ExportConfig.prototype.constructor = ExportConfig;

exports.ExportConfig = ExportConfig;
