/* This file is generated by IFramework - Maker.js for user to rewrite ListStore file */
!function () {
    var ExporterListStore = function ExporterListStore(db) {
    this.db = db;
    };

    ExporterListStore.prototype = new I.Models.ExporterListStoreBase();
    ExporterListStore.prototype.constructor = ExporterListStore;

    I.Util.require('ExporterListStore', 'Models', new ExporterListStore(db));
}();