/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var ExporterPK = function ExporterPK(pk) {
        this.init.call(this, pk);
    };

    ExporterPK.prototype = new I.Models.ExporterPKBase();
    ExporterPK.prototype.constructor = ExporterPK;

    I.Util.require('ExporterPK', 'Models', ExporterPK);
}();