/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var ExporterExistColumn = function ExporterExistColumn(args) {
        this.init.call(this, args);
    };

    ExporterExistColumn.prototype = new I.Models.ExporterExistColumnBase();
    ExporterExistColumn.prototype.constructor = ExporterExistColumn;

    I.Util.require('ExporterExistColumn', 'Models', ExporterExistColumn);
}();