/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Exporter = function Exporter(args) {
        this.init.call(this, args);
    };

    Exporter.prototype = new I.Models.ExporterBase();
    Exporter.prototype.constructor = Exporter;

    I.Util.require('Exporter', 'Models', Exporter);
}();