/* This file is generated by IFramework - Maker.js for user to rewrite PKStore file */
!function () {
    var ExporterExistColumnPKStore = function ExporterExistColumnPKStore(db) {
        this.db = db;
    };

    ExporterExistColumnPKStore.prototype = new I.Models.ExporterExistColumnPKStoreBase();
    ExporterExistColumnPKStore.prototype.constructor = ExporterExistColumnPKStore;

    I.Util.require('ExporterExistColumnPKStore', 'Models', new ExporterExistColumnPKStore(db));
}();