/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var StructureModel = function StructureModel() {
};

StructureModel.prototype = new StructureModelBase();
StructureModel.prototype.constructor = StructureModel;
exports.StructureModel = new StructureModel();