/* This file is generated by IFramework - Maker.js for user to rewrite ListStore file */
!function () {
    var TableListStore = function TableListStore(db) {
    this.db = db;
    };

    TableListStore.prototype = new I.Models.TableListStoreBase();
    TableListStore.prototype.constructor = TableListStore;

    I.Util.require('TableListStore', 'Models', new TableListStore(db));
}();