/* This file is generated by IFramework - Maker.js for user to rewrite List file */
!function () {
    var TableList = function TableList(pk, list) {
        this.init.call(this, pk, list);
    };

    TableList.prototype = new I.Models.TableListBase();
    TableList.prototype.constructor = TableList;

    I.Util.require('TableList', 'Models', TableList);
}();