/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var TableStore = function TableStore(db) {
    this.db = db;
    };

    TableStore.prototype = new I.Models.TableStoreBase();
    TableStore.prototype.constructor = TableStore;

    I.Util.require('TableStore', 'Models', new TableStore(db));
}();