/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Table = function Table(args) {
        this.init.call(this, args);
    };

    Table.prototype = new I.Models.TableBase();
    Table.prototype.constructor = Table;

    I.Util.require('Table', 'Models', Table);
}();