/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var TablePK = function TablePK(pk) {
        this.init.call(this, pk);
    };

    TablePK.prototype = new I.Models.TablePKBase();
    TablePK.prototype.constructor = TablePK;

    I.Util.require('TablePK', 'Models', TablePK);
}();