/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var Column = function Column(args) {
    this.init.call(this, args);
};

Column.prototype = new ColumnBase();
Column.prototype.constructor = Column;

Column.prototype.create = function create(listId) {
    iWebSocket.send('C0401', { listId: listId });
};

Column.prototype.update = function update(listId, column) {
    iWebSocket.send('C0402', { listId: listId, id: column.id, column: column.toAbbArray() });
};
