/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Exporter = function Exporter(args) {
        this.init.call(this, args);
    };

    Exporter.prototype = new I.Models.ExporterBase();
    Exporter.prototype.constructor = Exporter;

    Exporter.prototype.create = function create() {
        iWebSocket.send('C0801', {});
    };

    Exporter.prototype.update = function update() {
        iWebSocket.send('C0802', { id: this.id, exporter: this.toAbbDiff(), });
    };

    Exporter.prototype.remove = function remove() {
        iWebSocket.send('C0803', { id: this.id });
    };

    Exporter.prototype.updateRootTable = function updateRootTable() {
        iWebSocket.send('C0901', { id: this.id, tableId: this.rootTableId });
    };

    I.Util.require('Exporter', 'Models', Exporter);
}();
