/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
var TableList = function TableList(pk, list) {
    this.init.call(this, pk, list);
};

TableList.prototype = new TableListBase();
TableList.prototype.constructor = TableList;

TableList.prototype.retrieve = function retrieve() {
    iWebSocket.send('C0101');                       
};                                                  
