/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Table = function Table(args) {
        this.init.call(this, args);
    };

    Table.prototype = new I.Models.TableBase();
    Table.prototype.constructor = Table;

    Table.prototype.create = function create() {
        iWebSocket.send('C0201');
    };

    Table.prototype.update = function update() {
        iWebSocket.send('C0202', { id: this.id, table: this.toAbbDiff() });
    };

    Table.prototype.remove = function remove() {
        iWebSocket.send('C0203', { id: this.id });
    };

    I.Util.require('Table', 'Models', Table);
}();
